### PR TITLE
test: GCE output ends with .tar.gz

### PR DESCRIPTION
**Pull request by pastequo**
Following the change proposed here: https://github.com/osbuild/images/pull/987

### CODE REVIEW

**Review by mvo5 — COMMENTED** [review]
Thank you! I will approve once https://github.com/osbuild/images/pull/987 is merged, we will have to "go get -u github.com/osbuild/images@main" to get this fix too, I can do that once the branch has landed (if you are okay with me pushing to your branch)

**Review by mvo5 — APPROVED** [review]
Thank you!

**Review by achilleas-k — APPROVED** [review]

**Comment by achilleas-k** [comment]
```
Fetched layers: 383.43 MiB in 15 seconds (26.11 MiB/s)
ERROR Installing to filesystem: Creating ostree deployment: Pulling: Importing: Unencapsulating base: Failed to invoke skopeo proxy method FinishPipe: remote error: write |1: broken pipe
```
:thinking: 

flake?  Restarting

**Review by achilleas-k — CHANGES_REQUESTED** [review]
I know I already approved but can we have the commits reordered to make a bit more sense?
1. go.mod update.
2. test changes (squash the two).

Alternatively, since the test changes are so small, a single squashed commit would also be ok.

The current:
1. Test change
2. Update go.mod
3. Another test change

is a bit awkward.

**Comment by pastequo** [comment]
@achilleas-k commits reordered

**Review by achilleas-k — APPROVED** [review]
Thank you!

**Comment by pastequo** [comment]
Seems like it should be [cups-libs-2.4.11-1.fc40.x86_64.rpm](https://southfront.mm.fcix.net/fedora/linux/updates/40/Everything/x86_64/Packages/c/cups-libs-2.4.11-1.fc40.x86_64.rpm) instead

**Comment by pastequo** [comment]
Same error, this version `source/org.osbuild.curl (org.osbuild.curl): WARNING: failed to download https://ix-denver.mm.fcix.net/fedora/linux/updates/40/Everything/x86_64/Packages/c/cups-libs-2.4.10-7.fc40.x86_64.rpm: The requested URL returned error: 404` might be pinned somewhere...

**Pull request merged**
