### PR TITLE
Add missing volume mount to README

### PR DESCRIPTION
**Pull request by sshnaidm**
The current command fails if no mounted containers storage, add podman mount to fix it.

### CODE REVIEW

**Comment by p5** [comment]
Just a thought, and this could be completely wrong, but could you replace that /var mount with the user's rootless Podman storage directory, thus building in a rootful `podman run` command using the user's rootless Podman image?

**Comment by sshnaidm** [comment]
> Just a thought, and this could be completely wrong, but could you replace that /var mount with the user's rootless Podman storage directory, thus building in a rootful `podman run` command using the user's rootless Podman image?

AFAIK it doesn't support rootless podman currently.

**Comment by achilleas-k** [comment]
> Just a thought, and this could be completely wrong, but could you replace that /var mount with the user's rootless Podman storage directory, thus building in a rootful `podman run` command using the user's rootless Podman image?

I haven't tried this but I would worry about root taking ownership of files in the user's container store if it writes anything to it.  Easy to test though.

**Pull request merged**
