### PR TITLE
Multi-arch *4 support

### PR DESCRIPTION
**Pull request by lmilbaum**
Producing a multi-arch image build on the following arches: amd64, arm64, ppc64le and s390x

### CODE REVIEW

**Comment by lmilbaum** [comment]
@ondrejbudai @achilleas-k Please take a look at the CI failures. centos-bootc images multiarch support will be unlocked as soon as this PR is merged and an new quay.io/centos-bootc/bootc-image-builder image lands.

**Comment by mvo5** [comment]
This seems to fail because of a recent API change in the "images" library, this PR  https://github.com/osbuild/bootc-image-builder/pull/665 fix this and once rebased this test should pass.

**Comment by lmilbaum** [comment]
> This seems to fail because of a recent API change in the "images" library, this PR #665 fix this and once rebased this test should pass.

Thanks @mvo5 for your feedback. Is it safe to merge this PR even before the other fix has landed?

**Comment by achilleas-k** [comment]
#665 is in the merge queue.  We can rebase once it's merged to make sure the configs in this PR work.

**Review by achilleas-k — APPROVED** [review]

**Review by mvo5 — APPROVED** [review]
Thank you!

**Pull request merged**
