### PR TITLE
bib: run `dnf --version` in the container

### PR DESCRIPTION
**Pull request by hrismarin**
Recently, in bootc Base Images main branch the `dnf` package was replaced by `dnf5`.
See: https://gitlab.com/fedora/bootc/base-images/-/merge_requests/45

As a consequence `bootc-image-builder` now fails to build the `quay.io/fedora/fedora-bootc:42` image.
See: https://github.com/osbuild/bootc-image-builder/issues/650

Running plain `dnf` command in dnf5 output:
Missing command. Add "--help" for more information about the arguments.

The `dnf --version` command does not output non-zero exit code in both dnf and dnf5.

### CODE REVIEW

**Comment by henrywang** [comment]
I reported an dnf5 issue https://bugzilla.redhat.com/show_bug.cgi?id=2313032

**Comment by hrismarin** [comment]
I think it has to do with the fact that dnf and dnf5 behave differently when running a plain `dnf` command (no options or arguments).

In case of dnf (dnf 4) it otputs the vesion info and the exit code is `0`.

In case of dnf5 the output is `Missing command. Add "--help" for more information about the arguments.` and the exit code is `2`. See https://dnf5.readthedocs.io/en/latest/dnf5.8.html#exit-codes.

Note that I am not making any changes to the `quay.io/fedora/fedora-bootc:42` image i.e. I'm not building a derived image. I'm just trying to build the image straight from the registry as I explained in https://github.com/osbuild/bootc-image-builder/issues/650.

Filing a dnf5 issue on Bugzilla was probably the better option. Sorry for the noise if this PR doesn't make sense.

**Comment by sigulete** [comment]
Same problem here when trying to create an image from `quay.io/fedora-ostree-desktops/kinoite:41`

**Review by supakeen — APPROVED** [review]
Can reproduce the exit codes vs dnf4/dnf5. I'm unsure if this actually initializes dnf when ran with `--version`? (cc @mvo5 / @achilleas-k).

**Comment by mvo5** [comment]
Sorry that we left you hanging here for so long, I suspect `dnf --version` is not quite equivalent to what we need but I'm trying to reproduce this now and add a test-case.

**Comment by ondrejbudai** [comment]
Running `dnf` is required to initialize repositories from `subscription-manager` and its dnf-plugin. I'm pretty sure that `dnf --version` doesn't do that (I ran a quick test).

My take on this is: let's not worry about DNF 5 here. Both RHEL 9 and 10 use DNF 4 and these are the only systems that support image mode and require subscriptions. So I would the following thing: if dnf is version 4, run `dnf`, else do nothing. Add a TODO to resolve this when RHEL 11 is going to be released (~3+ years).

**Comment by mvo5** [comment]
> Running `dnf` is required to initialize repositories from `subscription-manager` and its dnf-plugin. I'm pretty sure that `dnf --version` doesn't do that (I ran a quick test).
> 
> My take on this is: let's not worry about DNF 5 here. Both RHEL 9 and 10 use DNF 4 and these are the only systems that support image mode and require subscriptions. So I would the following thing: if dnf is version 4, run `dnf`, else do nothing. Add a TODO to resolve this when RHEL 11 is going to be released (~3+ years).

I opened https://github.com/osbuild/bootc-image-builder/pull/658 with an alternative idea that might give us both.

**Comment by hrismarin** [comment]
> So I would the following thing: if dnf is version 4, run dnf, else do nothing. Add a TODO to resolve this when RHEL 11 is going to be released (~3+ years).

Seems like a reasonable solution to me. Should I close this PR?

**Comment by mvo5** [comment]
> > So I would the following thing: if dnf is version 4, run dnf, else do nothing. Add a TODO to resolve this when RHEL 11 is going to be released (~3+ years).
> 
> Seems like a reasonable solution to me. Should I close this PR?

It seems as is this PR would need some work, either detecting dnf4/dnf5 (and ignoring dnf5 like Ondrej suggested) or going with the alteratnive idea, I would like to credit you in the other PR though, I will need to remember to update/force-push. The only downside of `dnf clean` (in the other PR) is that it is slow on dnf5, I will check if there is another way.

**Comment by hrismarin** [comment]
Please let me know if I can help with anything like testing etc.

**Comment by mvo5** [comment]
@hrismarin The PR in https://github.com/osbuild/bootc-image-builder/pull/658 has landed now so the next `bib` container build should work. I think we can close this PR then.

**Pull request closed without merging**
