### PR TITLE
bib: show progress on ami upload

### PR DESCRIPTION
**Pull request by mvo5**
While discussing UI issues one thing that came up was progress bars. This is a tiny draft that needs https://github.com/osbuild/images/pull/383 and with that should have a nice upload progress bar. It will also enable us a json progress bar using the same idea (wrapping an io.Reader around something that reports progress) later.

### CODE REVIEW

**Comment by mvo5** [comment]
The failure happens because it runs out of diskspace:
```
2024-02-04T09:15:29.1148980Z ⏱  Duration: 0s
2024-02-04T09:15:29.1149435Z org.osbuild.copy: 23b0ed2590de100ddc5a87ec85a2952c2f5bb052cf5d253614ddc4da053d7aac {
2024-02-04T09:15:29.1150157Z   "paths": [
2024-02-04T09:15:29.1150366Z     {
2024-02-04T09:15:29.1151173Z       "from": "input://tree/boot/vmlinuz-6.8.0-0.rc0.20240109git9f8413c4a66f.1.eln134.x86_64",
2024-02-04T09:15:29.1151891Z       "to": "tree:///images/pxeboot/vmlinuz"
2024-02-04T09:15:29.1152291Z     },
2024-02-04T09:15:29.1152631Z     {
2024-02-04T09:15:29.1153256Z       "from": "input://tree/boot/initramfs-6.8.0-0.rc0.20240109git9f8413c4a66f.1.eln134.x86_64.img",
2024-02-04T09:15:29.1153849Z       "to": "tree:///images/pxeboot/initrd.img"
2024-02-04T09:15:29.1154349Z     }
2024-02-04T09:15:29.1154590Z   ]
2024-02-04T09:15:29.1154905Z }
2024-02-04T09:15:29.1155925Z copying '/run/osbuild/inputs/tree/boot/vmlinuz-6.8.0-0.rc0.20240109git9f8413c4a66f.1.eln134.x86_64' -> '/run/osbuild/tree/images/pxeboot/vmlinuz'
2024-02-04T09:15:29.1158040Z cp: error copying '/run/osbuild/inputs/tree/boot/vmlinuz-6.8.0-0.rc0.20240109git9f8413c4a66f.1.eln134.x86_64' to '/run/osbuild/tree/images/pxeboot/vmlinuz': No space left on device
2024-02-04T09:15:29.1159196Z Traceback (most recent call last):
2024-02-04T09:15:29.1168460Z   File "/run/osbuild/bin/org.osbuild.copy", line 156, in <module>
2024-02-04T09:15:29.1169029Z     r = main(_args, _args["options"])
2024-02-04T09:15:29.1169363Z         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-02-04T09:15:29.1169874Z   File "/run/osbuild/bin/org.osbuild.copy", line 149, in main
2024-02-04T09:15:29.1170677Z     subprocess.run(cmd + [src, dst], check=True)
2024-02-04T09:15:29.1171191Z   File "/usr/lib64/python3.12/subprocess.py", line 571, in run
2024-02-04T09:15:29.1171867Z     raise CalledProcessError(retcode, process.args,
2024-02-04T09:15:29.1173625Z subprocess.CalledProcessError: Command '['cp', '-a', '--reflink=auto', '/run/osbuild/inputs/tree/boot/vmlinuz-6.8.0-0.rc0.20240109git9f8413c4a66f.1.eln134.x86_64', '/run/osbuild/tree/images/pxeboot/vmlinuz']' returned non-zero exit status 1.
2024-02-04T09:15:29.1175005Z 
```

**Comment by achilleas-k** [comment]
Didn't we fix the diskspace already?

**Comment by ochosi** [comment]
> > Didn't we fix the diskspace already?
> 
> I'm trying to get to the bottom of it in https://github.com/osbuild/bootc-image-builder/pull/148 - it's a bit slow going and frustrating though. I wish we just had bigger disks :) 

Why can't we have bigger disks?

**Comment by mvo5** [comment]
> > > Didn't we fix the diskspace already?
> > 
> > 
> > I'm trying to get to the bottom of it in #148 - it's a bit slow going and frustrating though. I wish we just had bigger disks :)
> 
> Why can't we have bigger disks?

AIUI it is not possible on GH to request bigger disks, this is mostly under control (for now) since #178 got merged so fingers crossed :)

**Comment by achilleas-k** [comment]
Conflicts :<

**Review by achilleas-k — CHANGES_REQUESTED** [review]
LGTM but needs conflicts resolved.

**Comment by mvo5** [comment]
> LGTM but needs conflicts resolved.

Conflicts are resolved now :)

**Review by achilleas-k — APPROVED** [review]
:tada:

**Pull request merged**
