### PR TITLE
doc:add --cpu host in virt-install cli

### LINKED ISSUE #287: Sample virt-install invocation for eln requires explicit CPU flag
I am trying generate an image  straight-up from readme example:

```
sudo podman run \
    --rm \
    -it \
    --privileged \
    --pull=newer \
    --security-opt label=type:unconfined_t \
    -v $(pwd)/config.json:/config.json \
    -v $(pwd)/output:/output \
    quay.io/centos-bootc/bootc-image-builder:latest \
    --type qcow2 \
    --config /config.json \
    quay.io/centos-bootc/fedora-bootc:eln
```
even tried same with : quay.io/centos-bootc/centos-bootc:stream9

On trying to boot I get : 
```
 Error : kernel panic: not syncing: Attempted to kill init! exit code =0x00007f00
```
image

### PR DESCRIPTION
**Pull request by say-paul**
fixes #287

### CODE REVIEW

**Comment by cgwalters** [comment]
(Personally I think telling people to copy-paste qemu invocations is unsustainable and we should drop these and refer to tools maintained elsewhere, but yep)

**Comment by cgwalters** [comment]
Hmm actually, we may want `--os-variant rhel9` here? I think that will help ensure the right baseline?

**Comment by ondrejbudai** [comment]
@say-paul Can you check that `--os-variant rhel9` also fixes the issue? I agree that this would be preferred.

**Comment by say-paul** [comment]
tried it with `rhl9`, `rhel9-unknown` , but ended up with issue #287

**Review by cgwalters — APPROVED** [review]
I think there's a better doc on this but see https://www.spinics.net/lists/centos-devel/msg22018.html

I'd expect that `--os-variant fedora-eln` would work here too.  But this fine.

**Pull request merged**
