### PR TITLE
fix: set fips in manifest according to our customizations

### PR DESCRIPTION
**Pull request by stevenperaltaf5**
addresses #708

### CODE REVIEW

**Review by cgwalters — COMMENTED** [review]
I don't know enough about this code to 100% say this is correct but it looks plausible.

Basically as long as we end up with `fips=1` on the Anaconda kernel commandline, that's what we want.

**Comment by mvo5** [comment]
Thanks, this looks good, I did a small followup in https://github.com/osbuild/bootc-image-builder/pull/715 that adds a (manifest level) test to ensure this does not regress.

**Review by mvo5 — APPROVED** [review]
I guess we also want to support this customization for non-iso images(?)

**Comment by mvo5** [comment]
I also did a small followup in https://github.com/osbuild/images/pull/1035 for non-iso bootc containers but there is an open questions if this should come via customization or the bootc container itself would set it.

**Comment by henrywang** [comment]
> I guess we also want to support this customization for non-iso images(?)

Only ISO use non-bootc to deploy image. bootc supports kargs. So for non-ISO, FIPS can be enabled in Containerfile. Just in case `fips=1` configured twice.

**Pull request merged**
