### PR TITLE
bib: move to cheggaaa/pb/v3

### LINKED ISSUE #246: Update github.com/cheggaaa/pb to the latest version
For some reason, we use the version 1, when there's a version 3. Let's try to fix that, or document why it's not possible.

### PR DESCRIPTION
**Pull request by mvo5**
There is a new version of cheggaaa/pb that we should use. Minor API changes and the output changes slightly.

Fixes #246

### CODE REVIEW

**Review by ondrejbudai — DISMISSED** [review]
Yay, thanks!

**Comment by mvo5** [comment]
So it seems like testing-farm fails but the URL with the failure log is not included in the GH action (https://github.com/sclorg/testing-farm-as-github-action/issues/130) and I also don't see how else I can access the log. I'm sure there was a second status at some point with a link to the testing farm result but I don't see it anymore.

**Comment by rhatdan** [comment]
Needs a rebase.

**Comment by jamacku** [comment]
Some logs are available in Job Summary: https://github.com/osbuild/bootc-image-builder/actions/runs/8188230378?pr=248#summary-22398042194

**Review by ondrejbudai — APPROVED** [review]
still awesome

**Review by ondrejbudai — DISMISSED** [review]

**Comment by ondrejbudai** [comment]
I think we need yet another rebase. :/ But I think that the CI is finally in a state when we can actually merge stuff (just merged two PRs).

**Review by kingsleyzissou — DISMISSED** [review]

**Review by schuellerf — APPROVED** [review]

**Pull request merged**
