### PR TITLE
.github: enable ARM builds

### PR DESCRIPTION
**Pull request by ondrejbudai**

### CODE REVIEW

**Review by teg — APPROVED** [review]
Thank you!

**Review by mvo5 — APPROVED** [review]
This looks very nice! Given that it already has two +1s, can we just merge it :) ? Or is something missing?

**Comment by achilleas-k** [comment]
We have RHTAP builds now so I think it's not needed?
Or do we want it as a secondary for some reason?

**Comment by lmilbaum** [comment]
I've just configured RHTAP pipeline to push the image to quay.io/centos-bootc namespace.
In case you find it valuable, the following GHA workflow push a multi-arch image - https://github.com/CentOS/centos-bootc-infra/blob/main/.github/workflows/build-and-push-image.yml

**Comment by teg** [comment]
This takes 2h to build, should we drop it in favour of RHTAP?

**Pull request closed without merging**
